cors:
  originPatterns: http://localhost:3000, http://localhost:8080
file:
  upload-dir: /Users/harlanpierre/Documents/Projetos/UploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3308/iphone_swap_center?useTimezone=true?serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  paths-to-match:
    - /api/**
    - /auth/**
  swagger-ui:
    use-root-path: true


